name: Terraform CI

on:
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-ci.yml'

jobs:
  terraform:
    name: Terraform Static Analysis & Compliance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5.0'

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: terraform/environments/prod

      - name: Terraform Init (for validation)
        run: terraform init -backend=false
        working-directory: terraform/environments/prod

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform/environments/prod

      - name: tfsec (Security Scanning)
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: terraform/environments/prod

      - name: Checkov (Best Practices & Compliance)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform/environments/prod 