name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/environments/**'
      - '.github/workflows/terraform-apply.yml'

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 # Or make dynamic if needed

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5.0'

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/environments/prod

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform/environments/prod 